config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :hairs
  devise_for :users, controllers: {sessions: 'devise/sessions'}

  #redirecting root route to users/sign_up
  root :to => redirect('/users/sign_in')

  get "trytheapp" => "notusers#tryTheApp"

  get "hairedit" => "hairs#edit"

  get 'comb1' => "combs#result1"

  get 'comb2' => "combs#result2"

  get 'comb3' => "combs#result3"


end

app/models/hair.rb
class Hair < ApplicationRecord
  belongs_to :category
end

app/controllers/hairs_controller.rb
class HairsController < ApplicationController
  before_action :set_hair, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Hair.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @hair = Hair.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @hair = Hair.new(hair_params)

    respond_to do |format|
      if @hair.save
        format.html { redirect_to @hair, notice: 'Hair was successfully created.' }
        format.json { render :show, status: :created, location: @hair }
      else
        format.html { render :new }
        format.json { render json: @hair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @hair.update(hair_params)
        format.html { redirect_to @hair, notice: 'Hair was successfully updated.' }
        format.json { render :show, status: :ok, location: @hair }
      else
        format.html { render :edit }
        format.json { render json: @hair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @hair.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Hair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hair
      @hair = Hair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hair_params
      params.fetch(:hair, {})
    end
end

app/helpers/hairs_helper.rb
module HairsHelper
end

app/views/hairs/edit.html.erb
<div class="top-bar-profile">
  <img src="/assets/logo.jpg" class="logo-img"/> 
</div>

<h1 class="ht-title">Select your hair type</h1>

<div class="icons-panel"> 
  <img src="/assets/hair_curly.png" class="image-icon"/>
  <img src="/assets/hair_kinky.png" class="image-icon"/>
  <img src="/assets/hair_straight.png" class="image-icon"/>
  <img src="/assets/hair_wavy.png" class="image-icon"/>
</div>

<h1 class="ht-title">Select your hair length</h1>

<div class="icons-panel"> 
  <img src="/assets/length_short.png" class="image-icon"/>
  <img src="/assets/length_medium.png" class="image-icon"/>
  <img src="/assets/length_long.png" class="image-icon"/>
</div>

app/views/hairs/index.html.erb
<div class="top-bar-profile">
  <img src="/assets/logo.jpg" class="logo-img"/>
  <%= link_to('Logout', destroy_user_session_path, method: :delete, :class => 'profile-logout') %>
</div>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>

  <div class="profile-area">
    <div class="user-data">
      <!-- fazer a rederização condicional aqui, para puxar os ico certo-->
      <img class="user-data-icon" src="/assets/null_icon.png" /> 
      <img class="user-data-icon" src="/assets/null_icon.png" /> 
    </div>
    
    <%= link_to 'Set Data', hairedit_path, class: 'generate-hc' %>
    <%= link_to 'short straight', comb1_path, class: 'generate-hc' %>
    <%= link_to 'medium kinky', comb2_path, class: 'generate-hc' %>
    <%= link_to 'long wavy', comb3_path, class: 'generate-hc' %>

  </div>
</table>

app/views/hairs/new.html.erb
<h1>New Hair</h1>

<%= render 'form', hair: @hair %>

<%= link_to 'Back', hairs_path %>

<!-- <% if user_signed_in? %> -->
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </li>
<!-- <% else %> -->
  <!-- <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li> -->
<!-- <% end %> -->

app/views/hairs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hair_path(@hair) %> |
<%= link_to 'Back', hairs_path %>
<li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
</li>